"use client";
import { useState } from "react";

type DocumentRow = { id: string; type: string; name: string; version: number; sizeBytes: number; sha256?: string };
type Preview = { property: { id: string; name: string; type?: string; city?: string; area?: string; address?: string }; items: Array<{ documentId: string; documentVersionId: string; name: string; type: string; version: number; sizeBytes: number; sha256: string; sourceType: string }>; expiresAt?: string };
export function ExportPanel({ propertyId }: { propertyId: string }) {
  const [documents, setDocuments] = useState<DocumentRow[]>([]);
  const [selected, setSelected] = useState<string[]>([]);
  const [includePropertyMetadata, setIncludePropertyMetadata] = useState(true);
  const [preview, setPreview] = useState<Preview | null>(null);
  const [packageId, setPackageId] = useState("");
  const [status, setStatus] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const load = async () => { setBusy(true); setError(""); try { const response = await fetch(`/api/documents?propertyId=${encodeURIComponent(propertyId)}`, { cache: "no-store" }); const body = await response.json() as { data?: { documents: DocumentRow[] }; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message || "Documents could not be loaded."); setDocuments(body.data.documents.filter((doc) => doc.sha256)); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Documents could not be loaded."); } finally { setBusy(false); } };
  const showPreview = async () => { setBusy(true); setError(""); try { const response = await fetch("/api/exports/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ propertyId, documentIds: selected, includePropertyMetadata, idempotencyKey: "preview" }) }); const body = await response.json() as { data?: Preview; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message || "Export preview could not be created."); setPreview(body.data); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Export preview could not be created."); } finally { setBusy(false); } };
  const confirm = async () => { setBusy(true); setError(""); try { const response = await fetch("/api/exports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ propertyId, documentIds: selected, includePropertyMetadata, idempotencyKey: crypto.randomUUID() }) }); const body = await response.json() as { data?: { id: string; status: string }; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message || "Export could not be queued."); setPackageId(body.data.id); setStatus(body.data.status); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Export could not be queued."); } finally { setBusy(false); } };
  const process = async () => { if (!packageId) return; setBusy(true); setError(""); try { await fetch("/api/exports/worker", { method: "POST" }); const response = await fetch(`/api/exports/${packageId}`, { cache: "no-store" }); const body = await response.json() as { data?: { status: string }; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message || "Export status could not be loaded."); setStatus(body.data.status); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "Export status could not be loaded."); } finally { setBusy(false); } };
  return <div className="surface bg-white p-4 space-y-3"><div><p className="font-serif text-[16px]">Secure export</p><p className="text-[13px] text-ink-muted">Select clean private records, preview the exact package, then confirm. Download links are authenticated, temporary, and revocable.</p></div><button onClick={() => void load()} className="h-10 rounded-full border border-line bg-white px-3 text-[14px]">{busy ? "Working…" : "Load clean documents"}</button>{documents.length ? <div className="space-y-2">{documents.map((doc) => <label key={doc.id} className="flex items-center gap-2 rounded-xl border border-line bg-white p-2 text-[14px]"><input type="checkbox" checked={selected.includes(doc.id)} onChange={() => setSelected((current) => current.includes(doc.id) ? current.filter((id) => id !== doc.id) : [...current, doc.id])} />{doc.name} <span className="text-ink-muted">· {doc.type} · v{doc.version}</span></label>)}<label className="flex items-center gap-2 text-[14px]"><input type="checkbox" checked={includePropertyMetadata} onChange={(event) => setIncludePropertyMetadata(event.target.checked)} /> Include property metadata in manifest</label><div className="flex gap-2"><button disabled={!selected.length || busy} onClick={() => void showPreview()} className="h-10 flex-1 rounded-full border border-forest text-forest text-[14px]">Preview</button>{preview ? <button disabled={busy} onClick={() => void confirm()} className="h-10 flex-1 rounded-full bg-forest text-white text-[14px]">Confirm queue</button> : null}</div></div> : null}{preview ? <div className="rounded-xl border border-line bg-white p-3 text-[13px]">Preview contains {preview.items.length} selected source record{preview.items.length === 1 ? "" : "s"}; each item includes version, provenance, size, and SHA-256. No bytes are downloaded during preview.</div> : null}{packageId ? <div className="rounded-xl border border-line bg-white p-3 text-[14px]"><p>Package {packageId.slice(0, 8)}… · {status}</p><button onClick={() => void process()} className="mt-2 h-9 rounded-full bg-forest px-3 text-white text-[13px]">Process locally</button>{status === "READY" ? <a href={`/api/exports/${packageId}/download`} className="ml-2 underline text-[13px]">Download temporary ZIP</a> : null}</div> : null}{error ? <p className="text-[13px] text-red-700">{error}</p> : null}</div>;
}
